sudo: false
language: c++
branches:
  only:
  - master
  - dev
  except: gh-pages
env:
  global:
  - GH_REPO_NAME: pycompwa
  - GH_REPO_REF: github.com/ComPWA/pycompwa.git
  - OMP_NUM_THREADS: 1
  - LANG: en_US.UTF-8
  - BASEPATH: "$TRAVIS_BUILD_DIR"
  - ROOTSYS: "$BASEPATH/root"
addons:
  homebrew:
    packages:
    - boost
    - gsl
    - python
    - pipenv
  apt:
    update: true
    packages:
    - libboost-all-dev
    - libgsl0-dev
install:
- cd $BASEPATH
- cmake --version
- pipenv install
- wget https://root.cern.ch/download/root_${ROOTBIN}.tar.gz
- tar xpvfz root_*.tar.gz > /dev/null 2>&1
- cd root
- source bin/thisroot.sh
- cd $BASEPATH
matrix:
  include:
  - os: osx
    osx_image: xcode10.2
    env:
    - TASK="clang, ROOT v6.18"
    - ROOTBIN="v6.18.04.macosx64-10.14-clang100"
    - PATH=/Users/travis/Library/Python/3.7/bin:$PATH
    before_install:
    - echo "Using system python version."
  - os: linux
    dist: bionic
    compiler: gcc
    env:
    - TASK="gcc7, ROOT v6.18"
    - ROOTBIN="v6.18.04.Linux-ubuntu18-x86_64-gcc7.4"
    before_install:
    - pyenv global 3.7.1
    - pip3 install pipenv
    before_deploy:
    - pip3 install scikit-build
    deploy:
      provider: pypi
      user: "__token__"
      password:
        secure: "ZTIPRR3OC7V0P/Ovv1dULLSJ1EMGf9XLn8CsRI+KlTbSLyx9qyiAvjSQsv92dGlMIB52Gqlp1ChQn9d+pKd0412DXWNLSiPHJad+QU+0LmLB/tz2l1lIhOeIM4HJCHRgsKHCojhUjgjUIK8XB/YznVIpVfyDgjGwu8FSUrSTMcZ+2OXpykqFS0YWZXkfNImPuWciboU1W2DUHBRs+uczsuHaYKjrUz90U7XRk7Y55+sg2oMYbGIJmsqzM6tiSoflyxc4DmPHDvO3RynvP8ZSqUAWy5X/8h7pXUwL96Z2hYmoUDOfkKRZHueJGM9Gq28Crkq+5NL4Hc5awTuxv9YLP6GYk18PV5WGdDzooPAce4TI8WWRD1pIZh5wq4XNl4Y/EBDdPhJEIlfSC3yYKQdC1cwGdv+7faytLMplKhJOzZGjXXqdTuuY6dByRaMnsP+oN2L98Fw5Y5fJQjyP0OKwzmQ6vYjVR8DOyILz2dDjmnC8wGSCcHsMorg4tCVyD4AiLZ3+tyBchfIKv1ztQknCsZ84KgiQSuF3HjaE4CwxWpO/h2pmFw+Rgv1B/aE2qrH0/gkzf3SJdBK79vEYMRIptREG7svZpXMU5zg/CvrjQm5WEs5svML4EwD9P68goyea9e2zb2r1HgcphRCLEFTbXJyW/QOEuZsKq6Xby9rkFLo="
      distributions: sdist
      on:
        branch: dev
      skip_existing: true

script:
- cd $BASEPATH
- pipenv run python setup.py  --generator "Unix Makefiles" --skip-generator-test install
  -- -- -j2
- cd tests
- if [ "$TRAVIS_OS_NAME" != "osx" ]; then pipenv run python -m pytest; fi
- cd $BASEPATH
